version: "3.2"

volumes:
  my-db:
services:
  httpdmedia:
        image: httpdmedia:latest
        deploy:
           replicas: 1
           mode: replicated
           resources:
             limits:
               cpus: "0.3"
        ports:
            - "8095:80"
  mysqlmedia:
        image: mysql:5.7
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.3"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_HOST: localhost
        ports:
         - "3306:3306"
        volumes:
         - my-db:/var/lib/mysql
         - ./mysql-dump:/docker-entrypoint-initdb.d
  adminer:
        image: adminer
        ports:
          - 8080:8080

