version: "3.2"

volumes:
  derby_volume:
    external: true
services:
  httpd:
        image: library/httpd:latest
        deploy:
           replicas: 1
           mode: replicated
           resources:
             limits:
               cpus: "0.3"
        ports:
            - "80:80"
            - "8080:8080"
  derby:
        image: opavlova/db-derby:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.5"
        ports:
          - "1527:1527"
        environment:
            user: "admin"
            password: "123456"
        volumes:
          - type: volume
            source: derby_volume
            target: /data/db
networks:
  overlay:


